Jinntec/Fore

src/ForeElementMixin.js
src/actions/fx-append.js
src/fore.js
src/fx-bind.js
src/fx-form.js
src/fx-instance.js
src/fx-model.js
src/getInScopeContext.js
src/ui/fx-control.js
src/xpath-evaluation.js

This fixes #9.
I also ran prettier over the new files. I did not do this for existing files because of the _massive_ code change that will just distract from the PR.
I will make a separate PR for running prettier.

Centralize XPath calls

---

index.js
src/functions/fx-function.js
src/fx-form.js
src/xpath-evaluation.js
test/function.test.js

Implement JavaScript functions

---

src/fx-form.js
test/template-expression.test.js

And add a unit test to prevent these oopsies in the future

Fix the XPath used to detect templates

---

demo/01-hi.html
demo/hello-json.html
demo/simple-tei-header-1.html
demo/simple-tei-header-2.html
demo/simple-tei-header-3.html
demo/simple-tei-header.html
demo/tei-header.html
demo/tei/header.xml
demo/tei/kant.xml
demo/tei/simple-header1.xml
demo/tei/simple-header2.xml
demo/test-jsdelivr.html
demo/zen-quotes.html
es-dev-server.config.js
package-lock.json
package.json
resources/demo.css
resources/fore.css
src/actions/fx-append.js
src/ui/abstract-control.js
src/ui/fx-repeat.js
src/xpath-evaluation.js
template/barebone-cdn.html
template/barebone-dist.html
template/barebone.html

* fix for append action to use repeat context
* additional demos
* new logtree() function to output nested details/summary elements for debugging instances
* value-changed event passes 'path' property of modelItem now
* some template files as a starter

Tei header

---

demo/hello-json.html

There are five automobiles. The modulo was seven. The code was broken every 6th and 7th day of the month.

Fix JSON example only working a few days per week

---

demo/while.html
src/actions/abstract-action.js

And add an example that tests the removal of active delayed actions: we should not perform actions
for those.

Improve readability of while/delay/if of actions

---

demo/codemirror.html
demo/docbook-bibliography.html
demo/docbook/bibliography.xml
doc/demos.html
src/fx-fore.js
src/xpath-evaluation.js
test/instance.test.js
test/template-expression.test.js

And specifically the XSLT-like `xpath-default-namespace` attribute
Lets discuss this before merging, because, technically,w e are deviating from spec a bit here

Add a concrete example of using namespaces

---

src/xpath-evaluation.js

Rewrite target object resolving to fix linting error

---

src/xpath-evaluation.js

This doubles the speed. The intended caching optimization was not kicking in!

Improve performance of making namespace resolvers

---

demo/test/prereq.html
src/DependencyNotifyingDomFacade.js
src/dep_graph.js
src/fx-bind.js

Fixes #111.
Also break off processing when cyclic graphs _are_ seen

Add workaround to prereq example for cyclic graph

---

demo/variables.html
src/ui/fx-repeat.js

And pass the correct context from repeat

Improve example for vars

---

doc/reference.html
src/actions/abstract-action.js
test/action.test.js

An add tests to ensure this will work forever. This fixes #118

Use correct inscopecontext for if and while in actions

---

demo/todo.css
demo/todo2.html
src/ui/abstract-control.js
src/ui/fx-output.js
test/refresh.test.js
test/trigger.test.js

Prevents possible bugs with templates over a class atribute, it will fully be overwritten later

Add readonly and required as attributes not as classes

---

src/fx-fore.js
src/xpath-evaluation.js

Do not recreate XML documents for AST parsing
Improve XPath for finding template strings

Improve performance

---

demo/functions.html
src/functions/fx-function.js
src/xpath-evaluation.js

Now with XQuery update facility!

Add more elaborate XQuery function example

---

demo/epidoc/pre.html

If an `msPart` cannot be found, do not crash, just ignore it.

Fix `pre.html` demo

---

src/actions/fx-replace.js

Needed to update any binds to newly created elements. See fx-insert for the insert counterpart

Also rebuild binds after a replace takes place

---

src/fx-submission.js

Allow submission to send credentials

---

cypress/e2e/nested-todo.cy.ts
demo/nested-todo.html

This should keep working for the repeat update work :wink:

Add E2E test for repeats

---

cypress/e2e/binding.cy.ts
demo/binding.html
src/ui/abstract-control.js

Fix required event not always being fired

---

demo/fun-with-actions.html

Update fun-with-actions.html delete x

---

cypress/e2e/master-detail.cy.ts
demo/master-detail.html
demo/repeat-in-switch.html
src/ui/fx-repeat.js

Make index changes refresh the UI

---

src/functions/registerFunction.js
test/function.test.js

Fix regular expression for functions

---

cypress/e2e/todo2.cy.ts
demo/todo2.html
src/ui/fx-repeatitem.js

Fix item-changed firing way too often

---

src/xpath-evaluation.js

Makes it easier to see what's up

fix(errors): output the XPath error when an XPath fails

---

cypress/e2e/submission2.cy.ts
demo/submission2.html
src/fx-submission.js

They need encodeURIComponent.
Plus, a test!
Fixes #318

fix(fx-submission): allow downloading files with special characters
